version: '3.7'
services:
  app:
    build: .
    working_dir: /app
    command: sh -c "(yarn check --integrity || yarn install) && yarn run dev"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - next:/app/.next
      - node_modules:/app/node_modules
    environment:
      PORT:
    networks:
      - default
volumes:
  next:
  node_modules:
